### ISSUE TITLE
Error on ng build with --prod flag

### ISSUE THREAD

**Issue by lukasT** [showpad/angular-in-viewport#10]
After installing version 1.2.4, I get following error on build with --prod --aot flags:

```
ERROR in node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts(3,49): error TS1005: '=' expected.
```

**Comment by lukasT** [comment]
after updating Typescript to 2.8.3, the error was gone. Seems to be because of the "unique" symbol.
Don't know if this is an open issue then anymore? Could be closed I guess?

**Comment by klaascuvelier** [comment]
Thanks for reporting @lukasT I will have a look at this asap.
